### ISSUE TITLE
Add Functions to create landscape and portrait quote images

### ISSUE THREAD

**Issue by mubaris** [gostudent/aurora#1]
You have to add 2 functions which will create landscape and portrait quote images.

**Steps**

1) Rename `Create` to `CreateSquare`
2) Create `CreateLand` with width = 1600 and height = 1200 similar to `Create`. Don't forget adjust `aSpace` and `qSpace` accordingly
3) Create `CreatePort` width = 1200 and height = 1600 similar to `Create`. Don't forget adjust `aSpace` and `qSpace` accordingly

**Comment by pani-vishal** [comment]
I'd like to take this.

**Comment by mubaris** [comment]
@falconis If you don't have any other issues assigned, take it

**Comment by pani-vishal** [comment]
I have just one other issue, which I'll solve today. I plan to work on this tomorrow. Will that be fine?

**Comment by mubaris** [comment]
@falconis Gooo ahead :stuck_out_tongue:

**Comment by pani-vishal** [comment]
I'll complete this issue tomorrow....
