### ISSUE TITLE
Fix Codacy Issues

### ISSUE THREAD

**Issue by mubaris** [gostudent/aurora#19]
Solve issues from Codacy - https://www.codacy.com/app/mubaris/aurora/issues/index?&filters=W3siaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJDb2RlIFN0eWxlIl19XQ==

**Comment by pani-vishal** [comment]
I'd like to do this..

**Comment by pani-vishal** [comment]
Right now there are no issues on codacy...

**Comment by mubaris** [comment]
2 Issues were there 😄 
So closing this
