### ISSUE TITLE
Add Codacy Badge to Readme

### ISSUE THREAD

**Issue by mubaris** [gostudent/aurora#20]
You know the drill. Make sure the badge is in rectangular shape

**Comment by gauthamzz** [comment]
everybody knows the drill captian 🎖

**Comment by pani-vishal** [comment]
Can I do this too?

**Comment by gauthamzz** [comment]
How many issues do you have pending?

**Comment by pani-vishal** [comment]
2 but I thought this was a quick fix, so I asked...

**Comment by gauthamzz** [comment]
yeah sure. try to solve the pending 2. Then ask other issues.

**Comment by Jigar3** [comment]
Can I do it?

**Comment by mubaris** [comment]
`3cebbd0051d04bce90f0d15f21a092b8` is the project id. @Jigar3 Do it

**Comment by Jigar3** [comment]
Ok
