### ISSUE TITLE
Flexible Gradients

### ISSUE THREAD

**Issue by mubaris** [gostudent/aurora#22]
Right now, the user can only use pre-defined 2-color gradients. We need the following requirements

* Export and `gradient` datatype, so that user can create their own gradients.
	- Redefine `svg.OffColor` as `aurora.Color`. Only then the user will have access to it.
	- Instead of two field struct, `gradient` should be a slice of `svg.OffColor` / `aurora.Color`. This way user can create a gradient of more than 2 colors.

**Comment by pani-vishal** [comment]
I'd like to take this

**Comment by pani-vishal** [comment]
How do I redefine svg.Offcolor?
By writing this?
`type Color svg.Offcolor`?
Because if I do that... canvas.LinearGradient() wont accept type Color.

**Comment by mubaris** [comment]
`type Color svg.OffColor` Do this, then in `canvas.LinearGradient` use type assertion to convert back to `svg.OffColor`

**Comment by pani-vishal** [comment]
Ohhk thanks! Got it

**Comment by pani-vishal** [comment]
Is it fine if the user selects a gradient in the program he/she is writing?
Like:
`lg = aurora.Gradient[5]`
or 
creating his own gradient and passing it in Create function?

**Comment by mubaris** [comment]
They have to create their Gradient. That's the point

**Comment by pani-vishal** [comment]
Okay thanks!
