### ISSUE TITLE
Add More Gradients

### ISSUE THREAD

**Issue by mubaris** [gostudent/aurora#4]
Take all the gradients from https://gradients.cssgears.com/ and add it to aurora.

* Create a data type `gradient` with 2 color fields.

* Create an array of `gradient`s with all the gradients and export it.

* Change function definitions with optional gradient parameter.

**Comment by pani-vishal** [comment]
I'd like to take this

**Comment by pani-vishal** [comment]
Can I create a 2-d array of svg.Offcolor and name it gradients? @mubaris

**Comment by mubaris** [comment]
Sure

**Comment by pani-vishal** [comment]
So, is it necessary to create a new data type gradient then?

**Comment by mubaris** [comment]
Yes. Make a new type with 2 fields of datatype svg.OffColor

**Comment by falconis** [comment]
Yes I did that but it's now allowing me to pass the argument lg in
`canvas.LinearGradient("bb", 0, 0, 100, 100, lg)`
when lg is one of the element of the data gradient.

**Comment by pani-vishal** [comment]
Got it thanks!!
